server:
  servlet:
    context-path: /api
  port: 8888

spring:
  application:
    name: recomme_BE

com:
  example:
    firebase:
      web-api-key: AIzaSyAGEUVFK5U8ZzdFbIvHhsix_BRKoMUkOyo
      private-key: private-key.json