server:
  servlet:
    context-path: /api
  port: ${PORT:8888}

spring:
  application:
    name: recomme_BE
  data:
    mongodb:
      uri: ${MONGODB_URI}

com:
  example:
    firebase:
      web-api-key: ${FIREBASE_WEB_API_KEY}
      private-key: private-key.json
tmdb:
  api:
    key: ${TMDB_API_KEY}