server:
  servlet:
    context-path: /api
  port: 8888

spring:
  application:
    name: recomme_BE

com:
  example:
    firebase:
      web-api-key: AIzaSyDsRZMGfdM_zZEUmaaBG1E2BqlIAOem5rM
      private-key: private-key.json