server:
  servlet:
    context-path: /api
  port: 8888

spring:
  application:
    name: recomme_BE

com:
  example:
    firebase:
      web-api-key: ${FIREBASE_WEB_API_KEY}
      private-key: private-key.json
tmdb:
  api:
    key: ${TMDB_API_KEY}